#!/usr/bin/env bash
# Bash script to create an RSA key pair named 'school' with 4096 bits and passphrase 'betty'

# Create RSA private key 'school' with 4096 bits and passphrase 'betty'
ssh-keygen -t rsa -b 4096 -f school -N "betty"

