#!/usr/bin/env bash
# Bash script to generate a 4096-bit RSA key named 'school' with passphrase 'betty' and correct permissions

rm -f school school.pub && ssh-keygen -t rsa -b 4096 -f school -N "betty" && chmod 600 school && chmod 644 school.pub

